require_relative './models/base'
require_relative './models/battle'
require_relative './models/board'
require_relative './models/geometry'
require_relative './models/power_up'
require_relative './models/robot'
require_relative './models/square'
require_relative './models/turn'
